name: Deploy my next.js blog
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    concurrency: production
    steps:
      - uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18"
         
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run export

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
